language: generic

sudo: required

services: 
  - docker

before_install: 
  - docker build -t majinbisht/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true majinbisht/react-test npm run test

after_success: 
  - docker build -t majinbisht/multi-client -f ./client 
  - docker build -t majinbisht/multi-server -f ./server 
  - docker build -t majinbisht/multi-nginx -f ./nginx
  - docker build -t majinbisht/multi-worker -f ./worker 
  # first do dockerhub login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # now take those images and push it to docker hub
  - docker push majinbisht/multi-client
  - docker push majinbisht/multi-server
  - docker push majinbisht/multi-nginx
  - docker push majinbisht/multi-worker
  