language: generic

sudo: required

services: 
  - docker

before_install: 
  - docker build -t majinbisht/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true majinbisht/react-test npm run test

after_success: 
  - docker build -t majinbisht/multi-client ./client 
  - docker build -t majinbisht/multi-server ./server 
  - docker build -t majinbisht/multi-nginx  ./nginx
  - docker build -t majinbisht/multi-worker ./worker 
  # first do dockerhub login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # now take those images and push it to docker hub
  - docker push majinbisht/multi-client
  - docker push majinbisht/multi-server
  - docker push majinbisht/multi-nginx
  - docker push majinbisht/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-961492333341"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY